// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwnngoxzljdkcwkgkyqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3bm5nb3h6bGpka2N3a2dreXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDQ4NzgsImV4cCI6MjA2MTkyMDg3OH0.BbJbVL4WaPZ8BTBgGv6qY9GHj4fGMk_0h0KGr4bTaw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);